#!/usr/bin/bash
# USAGE: crypt pem-file key-file < input > output
#   encrypt input to output
#
# USAGE: crypt pem-file key-file -d < input > output
#   decrypt input to output
#
# USAGE: crypt pem-file key-file -d -in input > output
#   decrypt input to output
#
# USAGE: crypt pem-file key-file -out output < input
#   encrypt input to output

pem="$1"
key="$2"
shift 2

export SECRET_PASS=$(openssl base64 -d -in "$key" | openssl pkeyutl -decrypt -inkey "$pem" | openssl base64 -A)
openssl enc -aes-256-ctr -nosalt -base64 -pass env:SECRET_PASS "$@"
unset SECRET_PASS

